### ISSUE TITLE
Journaling with Joplin

### ISSUE THREAD

**Issue by bepolymathe** [ahaltindis/joplin-plugin-bulk-note-creator#1]
Hi @ahaltindis  

Thank you for this plugin !
 I need help. I would like to know if it would be possible to create notes with the date as the title ? My idea is to journaling in Joplin so have a notebook with all the dates of the current year in it.
 
It would be possible thanks to your plugin ? I can't configure it properly ?

**Comment by ahaltindis** [comment]
Hey @bepolymathe 

Yes, it is possible.

Plugin supports two different recurrence patterns at the moment, using one of them will be enough for your case. If you need one note for everyday, then select all days of the week for the `Recurrence 1`, provide a start date (31/12/2022) considering you want from start of the year - check the note in the end, start date will be excluded) and then how many notes you want in total (you want this to be 365/366 but just keeping short for testing). Use `rec1` parameter in your note title and body however you'd like with the date/time format of your preference (e.g `{rec1|YYYY-MM-DD}`).

<img width="476" alt="image" src="https://user-images.githubusercontent.com/1897850/183289149-ec67b3bd-539f-48ea-8f7b-b98b1a51c6db.png">

<img width="477" alt="image" src="https://user-images.githubusercontent.com/1897850/183289627-50c82a22-afb6-4732-9508-e9b00d9e66d5.png">

Which will create these notes in your notebook:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/1897850/183289556-1380798c-50a2-4da0-9b77-1bfdf4cf093d.png">

**Note:** I noticed a bug (or feature!) in this screenshoot, it seems I am excluding start date, so you can workaround this via setting the start date accordingly.

**Comment by bepolymathe** [comment]
Thanks for reply👍 It works !
